name: test

runs:
  steps:
      - run: git submodule update --init -- .style
        shell: bash
      - run: wget https://cs.symfony.com/download/php-cs-fixer-v2.phar
      - run: php php-cs-fixer-v2.phar fix --config=.style/.php_cs -v --dry-run --allow-risky=yes .
