name: Run Tests
description: 'Runs phpunit test uisng the stubs submodule' 
inputs:
  phpunit-version: 
    description: 'The version of phpunit which us used'
    required: false
    default: ''


runs:
  using: "composite"
  steps:
       - run: chmod +x $GITHUB_ACTION_PATH/script.sh {{ inputs.phpunit-version }}
         shell: bash
