name: Run Tests
description: 'Runs phpunit test uisng the stubs submodule' 
inputs:
  phpunit-version: 
    description: 'The version of phpunit which us used'
    required: false
    default: ''


runs:
  using: "composite"
  steps:
      - if: false
        run: echo 'asdf'
        shell: bash
      - run: wget https://phar.phpunit.de/phpunit${{ inputs.phpunit-version }}.phar
        shell: bash
      - run: phpdbg -qrr phpunit.phar tests --configuration tests/phpunit.xml
        shell: bash
