name: test

runs:
  steps:
      - run: wget https://cs.symfony.com/download/php-cs-fixer-v2.phar
        shell: bash
      - run: phpdbg -qrr phpunit.phar tests --configuration tests/phpunit.xml
        shell: bash
