# This is a basic workflow to help you get started with Actions

name: test-style

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  style:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master

    - name: Only fetch Style PHP submodule
      run: git submodule update --init -- .style

    - name: Install latest PHP-CS-Fixer
      run: wget https://cs.symfony.com/download/php-cs-fixer-v2.phar

    - name: Run Checks
      run: php php-cs-fixer-v2.phar fix --config=.style/.php_cs -v --dry-run --allow-risky=yes .
  
  test:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
      with:
          submodules: true

    - name: Install latest PHPUnit
      run: wget https://phar.phpunit.de/phpunit.phar

    - name: Run Tests
      run: phpdbg -qrr phpunit.phar tests --configuration tests/phpunit.xml
